# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harish Veerasekaran
email: hponenonly@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is harish.
  Love to write code, especially javascript, SASS and meaningful HTML.
  I like the Node environment, Atom text editor and GIT source control.
  While not writing code, I am mostly reading a book.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blenderous.github.io" # the base hostname & protocol for your site
twitter_username: blenderous
github_username:  blenderous

# Build settings
markdown: kramdown
